### ISSUE TITLE
is:advanceable missing cards

### ISSUE THREAD

**Issue by RomeoSierra** [Nephralite/cataloguer#9]
Searching with "is:advancable" does not include all Advanceable non-agendas.

Standard + Advanceable is missing cards (e.g.: NGO Front)
https://cataloguer.web.app/?search=z%3Astandard%20is%3Aadvanceable

Removing the "z:standard" term only adds Drago and Mausolus
https://cataloguer.web.app/?search=is%3Aadvanceable

**Comment by Nephralite** [comment]
hmm that's a just a fun problem with non-unified wording, nsg uses "you can advance this", but ffg uses "can be advanced", hadn't noticed as a startup player so will push a fix shortly
